[workspace]
members = ["crates/bootloader", "crates/kernel-main"]
resolver = "2"

[workspace.dependencies]
log = "0.4.22"
uefi = { version = "0.33.0", features = ["logger", "panic_handler", "qemu"] }
